In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Data/SMSSpamCollection.txt",sep="\t",names=['label','message'])

In [3]:
df

,label,message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."
...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...
5568,ham,Will ü b going to esplanade fr home?
5569,ham,"Pity, * was in mood for that. So...any other s..."
5570,ham,The guy did some bitching but I acted like i'd...


### Data Preprocessing and Data Cleaning

In [4]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [5]:
lemmatizer=WordNetLemmatizer()

In [6]:
stopwords = stopwords.words('english')
# stopwords

In [7]:
df.shape

(5572, 2)

In [8]:
len(df)

5572

In [16]:
corpus = []

for i in range(0,len(df)):
    review = re.sub('[^a-zA-Z]'," ",df['message'][i])
    review = review.lower().split()
    review = [lemmatizer.lemmatize(word) for word in review if not word in stopwords]
    review = " ".join(review)
    corpus.append(review)

In [12]:
df['message'][0]

'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'

In [20]:
print(corpus[0])

go jurong point crazy available bugis n great world la e buffet cine got amore wat


### Creat Bag of Words

In [21]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=100)

In [24]:
X = cv.fit_transform(corpus).toarray()

In [25]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [26]:
X.shape

(5572, 100)

In [27]:
cv.vocabulary_

{'go': np.int64(23),
 'great': np.int64(27),
 'got': np.int64(26),
 'wat': np.int64(89),
 'ok': np.int64(58),
 'free': np.int64(19),
 'win': np.int64(93),
 'text': np.int64(77),
 'txt': np.int64(85),
 'say': np.int64(68),
 'already': np.int64(0),
 'think': np.int64(80),
 'life': np.int64(39),
 'hey': np.int64(30),
 'week': np.int64(91),
 'back': np.int64(6),
 'like': np.int64(40),
 'still': np.int64(73),
 'send': np.int64(70),
 'friend': np.int64(20),
 'prize': np.int64(63),
 'claim': np.int64(10),
 'call': np.int64(7),
 'mobile': np.int64(49),
 'co': np.int64(11),
 'home': np.int64(32),
 'want': np.int64(88),
 'today': np.int64(82),
 'cash': np.int64(9),
 'day': np.int64(15),
 'reply': np.int64(65),
 'www': np.int64(96),
 'right': np.int64(66),
 'take': np.int64(75),
 'time': np.int64(81),
 'message': np.int64(46),
 'com': np.int64(12),
 'oh': np.int64(57),
 'yes': np.int64(99),
 'make': np.int64(44),
 'way': np.int64(90),
 'dont': np.int64(17),
 'miss': np.int64(48),
 'ur': np.int64(

In [36]:
print(sorted(list(cv.vocabulary_)))

['already', 'also', 'amp', 'anything', 'ask', 'babe', 'back', 'call', 'care', 'cash', 'claim', 'co', 'com', 'come', 'da', 'day', 'dear', 'dont', 'find', 'free', 'friend', 'get', 'give', 'go', 'going', 'good', 'got', 'great', 'gt', 'happy', 'hey', 'hi', 'home', 'hope', 'im', 'know', 'last', 'later', 'let', 'life', 'like', 'lor', 'love', 'lt', 'make', 'meet', 'message', 'min', 'miss', 'mobile', 'morning', 'msg', 'much', 'need', 'new', 'night', 'number', 'oh', 'ok', 'one', 'phone', 'please', 'pls', 'prize', 'really', 'reply', 'right', 'said', 'say', 'see', 'send', 'service', 'sorry', 'still', 'stop', 'take', 'tell', 'text', 'thanks', 'thing', 'think', 'time', 'today', 'tomorrow', 'tone', 'txt', 'uk', 'ur', 'want', 'wat', 'way', 'week', 'well', 'win', 'work', 'would', 'www', 'yeah', 'year', 'yes']


In [39]:
Sorted_vocab = sorted(list(cv.vocabulary_))
print(Sorted_vocab)

['already', 'also', 'amp', 'anything', 'ask', 'babe', 'back', 'call', 'care', 'cash', 'claim', 'co', 'com', 'come', 'da', 'day', 'dear', 'dont', 'find', 'free', 'friend', 'get', 'give', 'go', 'going', 'good', 'got', 'great', 'gt', 'happy', 'hey', 'hi', 'home', 'hope', 'im', 'know', 'last', 'later', 'let', 'life', 'like', 'lor', 'love', 'lt', 'make', 'meet', 'message', 'min', 'miss', 'mobile', 'morning', 'msg', 'much', 'need', 'new', 'night', 'number', 'oh', 'ok', 'one', 'phone', 'please', 'pls', 'prize', 'really', 'reply', 'right', 'said', 'say', 'see', 'send', 'service', 'sorry', 'still', 'stop', 'take', 'tell', 'text', 'thanks', 'thing', 'think', 'time', 'today', 'tomorrow', 'tone', 'txt', 'uk', 'ur', 'want', 'wat', 'way', 'week', 'well', 'win', 'work', 'would', 'www', 'yeah', 'year', 'yes']


In [42]:
Sorted_vocab[23]

'go'

In [41]:
for i in range(len(Sorted_vocab)):
    if Sorted_vocab[i] == "go":
        print(i)

23


In [31]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
0.343545

In [32]:
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000, 
    formatter=dict(float=lambda x: "%.4g" % x))

In [35]:
df['message'][0]

'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'

In [34]:
X[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [47]:
X[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [50]:
for i in range(len(X[0])):
    if X[0][i] == 1:
        print(i)    

23
26
27
89


In [55]:
Sorted_vocab[89]

'wat'

In [53]:
df['message'][0]

'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'

### N-grams

In [60]:
cv2 = CountVectorizer(max_features=100,binary=True,ngram_range=(2,3))
X2 = cv2.fit_transform(corpus).toarray()

In [61]:
print(X2[0])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [62]:
print(sorted(cv2.vocabulary_))

['account statement', 'attempt contact', 'await collection', 'call claim', 'call customer', 'call customer service', 'call identifier', 'call identifier code', 'call land', 'call land line', 'call landline', 'call later', 'call mobileupd', 'call optout', 'call per', 'cash prize', 'chance win', 'claim call', 'claim ur', 'claim valid', 'claim valid hr', 'co uk', 'code expires', 'customer service', 'dating service', 'decimal gt', 'dont know', 'double min', 'draw show', 'draw show prize', 'every week', 'free call', 'free entry', 'free text', 'good afternoon', 'good morning', 'good night', 'great day', 'gt lt', 'gt min', 'guaranteed call', 'guaranteed call land', 'gud ni', 'happy new', 'happy new year', 'holiday cash', 'hope good', 'identifier code', 'identifier code expires', 'land line', 'land line claim', 'land row', 'last night', 'let know', 'like lt', 'like lt gt', 'line claim', 'lt decimal', 'lt decimal gt', 'lt gt', 'lt gt min', 'national rate', 'nd attempt', 'new year', 'nice day', 

In [63]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [64]:
tfidf=TfidfVectorizer(max_features=100)

X=tfidf.fit_transform(corpus).toarray()

In [65]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.4342, 0, 0, 0.4612, 0.544, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.5503, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.4563, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0.473, 0, 0, 0, 0, 0, 0, 0, 0.4919, 0, 0, 0, 0, 0, 0, 0, 0.5711, 0, 0, 0, 0, 0, 0],
       [0.4649, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.4855, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.574, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 