### 1. Importing Necessary Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.datasets import load_wine

In [3]:
import warnings
warnings.filterwarnings('ignore')

#### Reading Data

In [4]:
data = load_wine()

### 2. Understanding the Dataset

In [5]:
print('Descripation of Dataset:',data.DESCR)

Descripation of Dataset: .. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

:Number of Instances: 178
:Number of Attributes: 13 numeric, predictive attributes and the class
:Attribute Information:
    - Alcohol
    - Malic acid
    - Ash
    - Alcalinity of ash
    - Magnesium
    - Total phenols
    - Flavanoids
    - Nonflavanoid phenols
    - Proanthocyanins
    - Color intensity
    - Hue
    - OD280/OD315 of diluted wines
    - Proline
    - class:
        - class_0
        - class_1
        - class_2

:Summary Statistics:

============================= ==== ===== ======= =====
                                Min   Max   Mean     SD
============================= ==== ===== ======= =====
Alcohol:                      11.0  14.8    13.0   0.8
Malic Acid:                   0.74  5.80    2.34  1.12
Ash:                          1.36  3.23    2.36  0.27
Alcalinity of Ash:            10.6  30.0    19.5   3.3
Magnesium:                   

In [6]:
print("Keys in the dataset:")
for feature in data.keys():
    print(f" - {feature}")

Keys in the dataset:
 - data
 - target
 - frame
 - target_names
 - DESCR
 - feature_names


#### Independent Variable and Dependent Variable

In [7]:
X = data['data']
y = data['target']
print("Dimension of Independent Variable:",X.shape)
print("Dimension of Dependent   Variable:",y.shape)

Dimension of Independent Variable: (178, 13)
Dimension of Dependent   Variable: (178,)


#### Features Name

In [8]:
print("Feature Names:")
for feature in data.feature_names:
    print(f" - {feature}")

Feature Names:
 - alcohol
 - malic_acid
 - ash
 - alcalinity_of_ash
 - magnesium
 - total_phenols
 - flavanoids
 - nonflavanoid_phenols
 - proanthocyanins
 - color_intensity
 - hue
 - od280/od315_of_diluted_wines
 - proline


#### i) Convert it into DataFrame

In [9]:
data['target_names']

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [10]:
df1 = pd.DataFrame(data['data'],columns=data['feature_names'])
df2 = pd.DataFrame(data['target'],columns=['Class'])

In [11]:
df = pd.concat([df1,df2],axis=1)
df.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,Class
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0


#### ii) Determining missing values

In [12]:
print('Missing Values:\n')
print(df.isnull().sum())

Missing Values:

alcohol                         0
malic_acid                      0
ash                             0
alcalinity_of_ash               0
magnesium                       0
total_phenols                   0
flavanoids                      0
nonflavanoid_phenols            0
proanthocyanins                 0
color_intensity                 0
hue                             0
od280/od315_of_diluted_wines    0
proline                         0
Class                           0
dtype: int64


### 3. Creating training , test dataset for  Dependent and Independent vaiable

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25,random_state=30)

In [15]:
print('Dimension of Training Dataset :-',X_train.shape)
print('Dimension of Test     Dataset :-',X_test.shape)

Dimension of Training Dataset :- (133, 13)
Dimension of Test     Dataset :- (45, 13)


### 4. Model Building

In [16]:
from sklearn.linear_model import LogisticRegression

In [17]:
Model_Lr = LogisticRegression()

##### Fitting the Model

In [18]:
Model_Lr.fit(X_train,y_train)

LogisticRegression()

##### Determining the Scores of Training and Testing Datasets

In [19]:
print(f"Training set score :- {Model_Lr.score(X_train,y_train)}")
print(f"Testing  set score :- {Model_Lr.score(X_test,y_test)}")

Training set score :- 0.9548872180451128
Testing  set score :- 0.9777777777777777


### 5. Predicting and determining accuracy of Model.

In [20]:
y_pred = Model_Lr.predict(X_test)
y_pred

array([1, 1, 2, 1, 2, 1, 2, 2, 0, 0, 1, 1, 0, 1, 1, 2, 0, 2, 0, 1, 0, 1,
       0, 1, 1, 1, 2, 1, 1, 1, 0, 2, 2, 0, 0, 1, 1, 2, 1, 0, 1, 0, 0, 2,
       1])

### 6. Performance Metrics  

In [21]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [22]:
cm = confusion_matrix(y_test,y_pred)
print(f'Results of the confusion Matrix :-\n {cm}')

Results of the confusion Matrix :-
 [[13  1  0]
 [ 0 20  0]
 [ 0  0 11]]


In [23]:
print(f'Classification Report :-\n{classification_report(y_test,y_pred)}')

Classification Report :-
              precision    recall  f1-score   support

           0       1.00      0.93      0.96        14
           1       0.95      1.00      0.98        20
           2       1.00      1.00      1.00        11

    accuracy                           0.98        45
   macro avg       0.98      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45



In [24]:
print(f'Accuracy :- {accuracy_score(y_test,y_pred)}')

Accuracy :- 0.9777777777777777
