<img alt="Logo" caption="Pytorch logo" src="../Image/Pytorch_logo.png"> 

## 1. What is PyTorch?

**PyTorch** is an open-source machine learning and deep learning framework primarily developed by Meta's AI Research lab. Based on the Torch library, it is highly flexible, easy to debug, and feels very "Pythonic." It allows researchers and developers to build dynamic neural networks that can be modified on the fly.

## Who Uses PyTorch?

PyTorch is an industry standard used by top technology companies to power major AI products and services:

* **Meta Platforms (Facebook):** Developed PyTorch; uses it extensively for computer vision, NLP, and AI research across Facebook and Instagram.
* **OpenAI:** Utilizes PyTorch for training large-scale language models and generative models, including GPT Models, ChatGPT, and DALL·E.
* **Microsoft:** Integrates PyTorch into Azure Machine Learning, Bing Search, and Office 365 Intelligent Features.
* **Tesla:** Uses PyTorch for training deep neural networks in computer vision and perception tasks critical for Autopilot and Full Self-Driving (FSD).
* **Uber:** Employs PyTorch for demand forecasting, route optimization, and developed *Pyro*, a probabilistic programming language built on PyTorch.

## 2. Core Features

PyTorch's architecture is built around several key features that make it a favorite among data scientists:

1. **Tensor Computations:** Multi-dimensional arrays similar to NumPy, but heavily optimized for deep learning.
2. **GPU Acceleration:** Tensors and mathematical operations can be easily moved to GPUs for massive speedups.
3. **Dynamic Computation Graph:** PyTorch builds the mathematical graph as your code runs (define-by-run), making debugging incredibly intuitive.
4. **Automatic Differentiation:** An engine that automatically computes derivatives (gradients) for all tensor operations, which is essential for training models.
5. **Distributed Training:** Natively supports scaling training jobs across multiple GPUs and machines.
6. **Interoperability with other libraries:** Blends seamlessly with Python's data science stack (like NumPy and SciPy).

## 3. Core PyTorch Modules


When building models, you will primarily interact with these fundamental building blocks:

| Module | Description |
| --- | --- |
| `torch` | The core module providing multidimensional arrays (tensors) and mathematical operations on them. |
| `torch.autograd` | Automatic differentiation engine that records operations on tensors to compute gradients for optimization. |
| `torch.nn` | Provides a neural networks library, including layers, activations, loss functions, and utilities to build deep learning models. |
| `torch.optim` | Contains optimization algorithms (optimizers) like SGD, Adam, and RMSprop used for training neural networks. |
| `torch.utils.data` | Utilities for data handling, including the `Dataset` and `DataLoader` classes for managing and loading datasets efficiently. |
| `torch.jit` | Supports Just-In-Time (JIT) compilation and TorchScript for optimizing models and enabling deployment without Python dependencies. |
| `torch.cuda` | Interfaces with NVIDIA CUDA to enable GPU acceleration for tensor computations and model training. |
| `torch.backends` | Contains settings and allows control over backend libraries like cuDNN, MKL, and others for performance tuning. |
| `torch.multiprocessing` | Utilities for parallelism using multiprocessing, similar to Python's `multiprocessing` module but with support for CUDA tensors. |
| `torch.onnx` | Supports exporting PyTorch models to the ONNX format for interoperability with other frameworks and deployment. |

## 4. Popular PyTorch Ecosystem Libraries

PyTorch is backed by a massive ecosystem that prevents you from having to "reinvent the wheel" for specific tasks.

### Domain-Specific Libraries & Wrappers

| Library | Description |
| --- | --- |
| `torchvision` | Provides datasets, model architectures, and image transformations for computer vision tasks. |
| `torchtext` | Tools and datasets for natural language processing (NLP), including data preprocessing. |
| `torchaudio` | Utilities for audio processing tasks, including I/O, transforms, and pre-trained models. |
| `torchserve` | A model serving library that makes it easy to deploy trained models at scale in production. |
| `pytorch_lightning` | A lightweight wrapper that simplifies the training loop and reduces boilerplate code, enabling scalable models. |

### Ecosystem Tools & Extensions

| Library | Description |
| --- | --- |
| **Hugging Face Transformers** | Provides state-of-the-art pre-trained models for NLP tasks (built on PyTorch). |
| **Fastai** | High-level library that simplifies training fast and accurate neural nets using modern best practices. |
| **PyTorch Geometric** | Extension library for geometric deep learning, including graph neural networks. |
| **TorchMetrics** | A modular metrics API for PyTorch, providing standardized implementations of common metrics. |
| **Optuna** | Automatic hyperparameter optimization software framework for tuning models. |
| **AllenNLP** | An NLP research library designed to support researchers in deep learning for NLP. |
| **Skorch** | A scikit-learn compatible wrapper for PyTorch. |
| **PyTorch Forecasting** | High-level library for time series forecasting. |
| **TensorBoard for PyTorch** | Allows visualization of training metrics, model graphs, and other useful data. |

## 5. Understanding Tensors in PyTorch

### What are Tensors?
At its core, a Tensor is a specialized multi-dimensional array designed specifically for mathematical and computational efficiency. You can think of them as the primary data structure in deep learning. While they are very similar to standard arrays, tensors are optimized to track dimensions (directions/span) and run on specialized hardware.

#### Real-World Examples of Tensors by Dimension:

<img alt="tensor_dimensions" caption="Pytorch tensor_dimensions" src="../Image/tensor_dimensions.png"> 

1. **Scalars (0-dimensional tensors):** A single number.
* *Usage:* Represents a single value, often used for simple metrics or constants.
* *Example:* **Loss value**. After a forward pass, the loss function computes a single scalar value indicating the difference between the predicted and actual outputs (e.g., `5.0` or `-3.14`).


2. **Vectors (1-dimensional tensors):** A list of numbers (arrays).
* *Usage:* Represents a sequence or a collection of values.
* *Example:* **Word Embeddings / Feature Vectors**. In Natural Language Processing (NLP), each word in a sentence may be represented as a 1D vector. (e.g., `[0.12, -0.84, 0.33]` from a pre-trained model like Word2Vec or GloVe).


3. **Matrices (2-dimensional tensors):** A 2D grid of numbers.
* *Usage:* Represents tabular or grid-like data.
* *Example:* **Grayscale Images**. A grayscale image can be represented as a 2D tensor, where each entry corresponds to the pixel intensity. (e.g., `[[0, 255, 128], [34, 90, 180]]`).


4. **3D Tensors:** Adds a third dimension, often used for stacking data.
* *Usage:* **Coloured Images (RGB)**.
* *Example:* A single RGB image is represented as a 3D tensor mapping `(width × height × channels)`. An image of size 256x256 with 3 color channels (Red, Green, Blue) has the shape `[256, 256, 3]`.


5. **4D Tensors:** Adds the batch size as an additional dimension to 3D data.
* *Usage:* **Batches of RGB images**.
* *Example:* A dataset of coloured images is represented as a 4D tensor mapping `(batch size × width × height × channels)`. A batch of 32 images, each size 128x128 with 3 color channels, has the shape `[32, 128, 128, 3]`.


6. **5D Tensors:** Adds a time dimension for data that changes over time.
* *Usage:* **Video data**. Video clips are represented as a sequence of frames, where each frame is an RGB image.
* *Example:* A batch of 10 video clips, where each clip has 16 frames of size 64x64 and 3 color channels, would have the shape `[10, 16, 64, 64, 3]`.

## 6. Why Are Tensors Useful?

1. **Mathematical Operations:** Tensors enable highly efficient mathematical computations (addition, multiplication, dot products, etc.) that are strictly necessary for neural network operations.
2. **Representation of Real-world Data:** Almost any data type can be numerically represented as a tensor:
* **Images:** 3D tensors `(width × height × channels)`.
* **Text:** Tokenized and represented as 2D or 3D tensors `(sequence length × embedding size)`.
* **Audio & Video:** Represented with time and frequency dimensions.


3. **Efficient Computations:** Tensors are explicitly optimized for hardware acceleration. This allows massive parallel computations on **GPUs** (Graphics Processing Units) or **TPUs**, which is absolutely crucial for training deep learning models in a reasonable amount of time.

## 8. Setting Up & Verifying PyTorch

In [1]:
import torch
print(torch.__version__)

2.11.0+cu130


In [2]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: NVIDIA GeForce RTX 3050 Laptop GPU


## 9. Creating Tensors

In [3]:
# using empty
a = torch.empty(2,3)
a

tensor([[1.2849e-01, 3.0873e-41, 0.0000e+00],
        [0.0000e+00, 4.4842e-44, 0.0000e+00]])

In [4]:
# check type
type(a)

torch.Tensor

In [5]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
# using rand
torch.rand(2,3)

tensor([[0.4165, 0.9290, 0.9422],
        [0.3318, 0.9240, 0.0241]])

**Manual seed**
A manual seed forces PyTorch's random number generator to start from the same point every time, which is essential in deep learning so that your results can be reproduced and compared fairly across different runs.

In [8]:
# use of seed
torch.rand(2,3) # produces random result every time, contradicts the lesso

tensor([[0.2705, 0.6043, 0.2925],
        [0.3765, 0.7450, 0.4483]])

In [9]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## 10. Tensor Shapes & Reshaping

In [13]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
x.shape

torch.Size([2, 3])

In [15]:
torch.empty_like(x)

tensor([[             0, 94649803127632,              0],
        [             0,              1,              6]])

In [16]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [17]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [18]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

- `Reshape()` changes the dimensions (shape) of an array or tensor without altering its underlying data or the total number of elements.

In [47]:
input_shape =  torch.randint(0,100,(9,))
print(f"{input_shape} \n {input_shape.shape}")

input_shape.reshape((3,3))

tensor([85, 96, 44, 84, 88, 29, 17, 15, 93]) 
 torch.Size([9])


tensor([[85, 96, 44],
        [84, 88, 29],
        [17, 15, 93]])

- `squeeze()` Removes any dimension that has a size of 1, which commonly comes up after batch processing when you have a leftover single-item dimension you no longer need.

In [ ]:
# 1. Create a "batch" containing one result with 10 classes
# Shape: (1, 10) -> [Batch, Classes]
output = torch.randn(1, 10)
print(f"Original Shape: {output.shape}")


# 2. Squeeze it to remove the batch dimension
# This turns it into a simple 1D vector of 10 elements
squeezed_output = output.squeeze()
print(f"Squeezed Shape: {squeezed_output.shape}")

- `unsqueeze()` inserts a new dimension of size 1 at a position you specify, which is often needed to match the shape a model or function expects, such as adding a batch dimension to a single image.

In [ ]:
# 1. Simulate a single RGB image (3 channels, 224x224 pixels)
# Shape: [3, 224, 224]
image = torch.randn(3, 224, 224)
print(f"Original Image Shape: {image.shape}")

# 2. Add the batch dimension at index 0
# This makes it a "batch of 1"
# Shape: [1, 3, 224, 224]
input_tensor = image.unsqueeze(0)
print(f"Model-Ready Shape:    {input_tensor.shape}")

- `flatten()` collapses all the dimensions of a tensor into a single long 1D vector, which is the standard step performed just before passing data into a fully connected (linear) layer.

In [50]:
input_dimension = torch.randint(1,10,(2,2))
print(input_dimension)

input_dimension.flatten()

tensor([[9, 3],
        [1, 9]])


tensor([9, 3, 1, 9])

- `permute()` rearranges the original dimensions of a tensor into a specific new order, allowing you to "shuffle" the axes themselves rather than just changing the numbers in the shape.

    - **The Scenario:** Changing Image Formats
      This is most common when moving between image libraries. Many visualization tools (like Matplotlib) expect images to be Channel-Last (Height, Width, Channels), while PyTorch models expect Channel-First (Channels, Height, Width)

In [55]:
# 1. Start with a Channel-Last image (e.g., from OpenCV or PIL)
# Shape: [224, 224, 3] -> (H, W, C)
image = torch.randn(224, 224, 3)
print(f"Original Shape (H, W, C): {image.shape}")

# 2. Permute to Channel-First for a PyTorch model
# We want: 
# Original Dim 2 (Channels) to be at index 0
# Original Dim 0 (Height) to be at index 1
# Original Dim 1 (Width) to be at index 2
permuted_image = image.permute(2,1,0)

print(f"Permuted Shape (C, H, W): {permuted_image.shape}")

Original Shape (H, W, C): torch.Size([224, 224, 3])
Permuted Shape (C, H, W): torch.Size([3, 224, 224])


## 11. Tensor Data Types

In [ ]:
# find data type
x.dtype

In [ ]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3], dtype=torch.float64)

In [ ]:
# using to()
x.to(torch.float32)

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## 12. Moving Tensors to a Device (CPU / GPU)

#### Moving Tensors to a Device (CPU / GPU)

In PyTorch, a **device** refers to the physical hardware where a tensor's data lives and where its computations are executed. This can be either:
- **CPU** (Central Processing Unit) - Default, works everywhere
- **GPU** (Graphics Processing Unit) - CUDA-enabled NVIDIA GPUs for massive speedups
- **MPS** (Metal Performance Shaders) - Apple Silicon (M1/M2/M3) acceleration

**Why this matters:**
- Neural network training on a GPU can be 10-100x faster than on CPU
- A tensor can only interact with other tensors on the **same device**
- All PyTorch operations require their input tensors to be on the same device

**Critical rule:** Tensors created on one device stay on that device until you explicitly move them.

In [56]:
import torch

# Check PyTorch version
print(f"PyTorch version: {torch.__version__}")
print()

# Check if CUDA (NVIDIA GPU) is available
if torch.cuda.is_available():
    print("✓ CUDA is available!")
    print(f"  GPU Device: {torch.cuda.get_device_name(0)}")
    print(f"  Number of GPUs: {torch.cuda.device_count()}")
else:
    print("✗ CUDA not available - using CPU")

print()

# Check if MPS (Apple Silicon) is available
if torch.backends.mps.is_available():
    print("✓ MPS (Apple Silicon) is available!")
else:
    print("✗ MPS not available")

PyTorch version: 2.11.0+cu130

✓ CUDA is available!
  GPU Device: NVIDIA GeForce RTX 3050 Laptop GPU
  Number of GPUs: 1

✗ MPS not available


## Mathematical operations

### 1. Scalar operation

In [ ]:
x = torch.rand(2,2)
x

In [ ]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

### 2. Element wise operation

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

In [ ]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

In [ ]:
c = torch.tensor([1, -2, 3, -4])

In [ ]:
# abs
torch.abs(c)

In [ ]:
# negative
torch.neg(c)

In [ ]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [ ]:
# round
torch.round(d)

In [ ]:
# ceil
torch.ceil(d)

In [ ]:
# floor
torch.floor(d)

In [ ]:
# clamp
torch.clamp(d, min=2, max=3)

### 3. Reduction operation

In [ ]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

In [ ]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

In [ ]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

In [ ]:
# median
torch.median(e)

In [ ]:
# max and min
torch.max(e)
torch.min(e)

In [ ]:
# product
torch.prod(e)

In [ ]:
# standard deviation
torch.std(e)

In [ ]:
# variance
torch.var(e)

In [ ]:
# argmax
torch.argmax(e)

In [ ]:
# argmin
torch.argmin(e)

### 4. Matrix operations

In [ ]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

In [ ]:
# matrix multiplcation
torch.matmul(f, g)

In [ ]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

In [ ]:
# transpose
torch.transpose(f, 0, 1)

In [ ]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

In [ ]:
# determinant
torch.linalg.det(h)

In [ ]:
# inverse
torch.linalg.inv(h)

### 5. Comparison operations

In [ ]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

In [ ]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to
i >= j

# less than equal to
i <= j

### 6. Special functions

In [ ]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

In [ ]:
# log
torch.log(k)

In [ ]:
# exp
torch.exp(k)

In [ ]:
# sqrt
torch.sqrt(k)

In [ ]:
# sigmoid
torch.sigmoid(k)

In [ ]:
# softmax
torch.softmax(k, dim=0)

In [ ]:
# relu
torch.relu(k)

## Inplace Operations

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

In [ ]:
m.add_(n)

In [ ]:
m

In [ ]:
n

In [ ]:
torch.relu(m)

In [ ]:
m.relu_()

In [ ]:
m

## Copying a Tensor

In [ ]:
a = torch.rand(2,3)
a

In [ ]:
b = a

In [ ]:
b

In [ ]:
a[0][0] = 0

In [ ]:
a

In [ ]:
b

In [ ]:
id(a)

In [ ]:
id(b)

In [ ]:
b = a.clone()

In [ ]:
a

In [ ]:
b

In [ ]:
a[0][0] = 10

In [ ]:
a

In [ ]:
b

In [ ]:
id(a)

In [ ]:
id(b)