In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [3]:
type(arr1)

numpy.ndarray

In [4]:
arr2 = np.array([[1,2],[3,4]])
arr2

array([[1, 2],
       [3, 4]])

In [5]:
arr3 = np.array([[[1,2],[3,4],[5,6]]])
arr3

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [8]:
# 1d array
print(arr1)
arr1.ndim

[1 2 3 4 5]


1

In [9]:
print(arr2)
arr2.ndim

[[1 2]
 [3 4]]


2

In [10]:
print(arr3)
arr3.ndim

[[[1 2]
  [3 4]
  [5 6]]]


3

In [12]:
arr4 = np.array([[[[1,2],[3,4],[5,6]]]])
arr4.ndim

4

In [14]:
arr2.dtype

dtype('int32')

In [17]:
# int32 --> 4 , int64 --> 8

np.array([1,2,3],dtype=int)

array([1, 2, 3])

In [18]:
np.array([1,2,3],dtype=int).dtype

dtype('int32')

In [20]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [23]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
# reshape

np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [27]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [30]:
np.arange(1,11).reshape(5,2,1)

array([[[ 1],
        [ 2]],

       [[ 3],
        [ 4]],

       [[ 5],
        [ 6]],

       [[ 7],
        [ 8]],

       [[ 9],
        [10]]])

In [31]:
# Zero 
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [32]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
# once
np.ones(5)

array([1., 1., 1., 1., 1.])

In [34]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
np.random.random((3,4))

array([[0.23200255, 0.82515759, 0.75368187, 0.80260531],
       [0.08989403, 0.1584749 , 0.05893019, 0.07137165],
       [0.69175825, 0.52548977, 0.86125286, 0.44548209]])

In [36]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [37]:
3.25 - 1

2.25

In [38]:
5.5 - 3.25

2.25

In [39]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
arr2.shape

(2, 2)

In [43]:
arr2

array([[1, 2],
       [3, 4]])

In [44]:
arr2.size

4

In [ ]:
np.eye()